helm-template:
  name: "order-service" 

  image:
    repository: order-service
    tag: 1
    pullPolicy: IfNotPresent
    port: 8080

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

  service:
    enabled: true
    type: ClusterIP
    port: 8080

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  ingress:
    enabled: false

  configmap:
    enabled: true
    name: order-service
    data:
      INVENTORY_SERVICE_URL: "http://inventory-service.inventory-service.svc.cluster.local:8080"
      SERVER_PORT: "8080"
  
  service-account:
    enabled: true
    name: order-service
    annotations:
      eks.amazonaws.com/role-arn: xxx
    automountServiceAccountToken: true

  externalSecrets:
    enabled: true
    key: order-service-secret

